// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mehspot.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MehspotResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MehspotResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mehspot.Core.MehspotResources", typeof(MehspotResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Babysitter {
            get {
                return ResourceManager.GetString("Babysitter", resourceCulture);
            }
        }
        
        public static string BabysitterEmployer {
            get {
                return ResourceManager.GetString("BabysitterEmployer", resourceCulture);
            }
        }
        
        public static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        public static string Friendship {
            get {
                return ResourceManager.GetString("Friendship", resourceCulture);
            }
        }
        
        public static string Golf {
            get {
                return ResourceManager.GetString("Golf", resourceCulture);
            }
        }
        
        public static string Hobby {
            get {
                return ResourceManager.GetString("Hobby", resourceCulture);
            }
        }
        
        public static string KidsPlayDate {
            get {
                return ResourceManager.GetString("KidsPlayDate", resourceCulture);
            }
        }
        
        public static string OtherJobs {
            get {
                return ResourceManager.GetString("OtherJobs", resourceCulture);
            }
        }
        
        public static string PetSitter {
            get {
                return ResourceManager.GetString("PetSitter", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer {
            get {
                return ResourceManager.GetString("PetSitterEmployer", resourceCulture);
            }
        }
        
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        public static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        public static string Tutor {
            get {
                return ResourceManager.GetString("Tutor", resourceCulture);
            }
        }
        
        public static string TutorEmployer {
            get {
                return ResourceManager.GetString("TutorEmployer", resourceCulture);
            }
        }
        
        public static string Babysitter_Description {
            get {
                return ResourceManager.GetString("Babysitter_Description", resourceCulture);
            }
        }
        
        public static string BabysitterEmployer_Description {
            get {
                return ResourceManager.GetString("BabysitterEmployer_Description", resourceCulture);
            }
        }
        
        public static string Fitness_Description {
            get {
                return ResourceManager.GetString("Fitness_Description", resourceCulture);
            }
        }
        
        public static string Friendship_Description {
            get {
                return ResourceManager.GetString("Friendship_Description", resourceCulture);
            }
        }
        
        public static string Golf_Description {
            get {
                return ResourceManager.GetString("Golf_Description", resourceCulture);
            }
        }
        
        public static string Hobby_Description {
            get {
                return ResourceManager.GetString("Hobby_Description", resourceCulture);
            }
        }
        
        public static string KidsPlayDate_Description {
            get {
                return ResourceManager.GetString("KidsPlayDate_Description", resourceCulture);
            }
        }
        
        public static string OtherJobs_Description {
            get {
                return ResourceManager.GetString("OtherJobs_Description", resourceCulture);
            }
        }
        
        public static string PetSitter_Description {
            get {
                return ResourceManager.GetString("PetSitter_Description", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer_Description {
            get {
                return ResourceManager.GetString("PetSitterEmployer_Description", resourceCulture);
            }
        }
        
        public static string Sports_Description {
            get {
                return ResourceManager.GetString("Sports_Description", resourceCulture);
            }
        }
        
        public static string Tennis_Description {
            get {
                return ResourceManager.GetString("Tennis_Description", resourceCulture);
            }
        }
        
        public static string Tutor_Description {
            get {
                return ResourceManager.GetString("Tutor_Description", resourceCulture);
            }
        }
        
        public static string TutorEmployer_Description {
            get {
                return ResourceManager.GetString("TutorEmployer_Description", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string BabysitterFirstName {
            get {
                return ResourceManager.GetString("BabysitterFirstName", resourceCulture);
            }
        }
        
        public static string BabysitterCanDrive {
            get {
                return ResourceManager.GetString("BabysitterCanDrive", resourceCulture);
            }
        }
        
        public static string BabysitterOwnCar {
            get {
                return ResourceManager.GetString("BabysitterOwnCar", resourceCulture);
            }
        }
        
        public static string BabysitterHourlyRate {
            get {
                return ResourceManager.GetString("BabysitterHourlyRate", resourceCulture);
            }
        }
        
        public static string BabysitterDescriptionDefault {
            get {
                return ResourceManager.GetString("BabysitterDescriptionDefault", resourceCulture);
            }
        }
        
        public static string BabysitterAdditionalInformation {
            get {
                return ResourceManager.GetString("BabysitterAdditionalInformation", resourceCulture);
            }
        }
        
        public static string BabysitterBabysitterCertificationInfoDefault {
            get {
                return ResourceManager.GetString("BabysitterBabysitterCertificationInfoDefault", resourceCulture);
            }
        }
        
        public static string BabysitterCertificationInfo {
            get {
                return ResourceManager.GetString("BabysitterCertificationInfo", resourceCulture);
            }
        }
        
        public static string BabysitterCertificationInfo_AHA_CPR {
            get {
                return ResourceManager.GetString("BabysitterCertificationInfo_AHA_CPR", resourceCulture);
            }
        }
        
        public static string BabysitterCertificationInfo_AHA_FirstAid {
            get {
                return ResourceManager.GetString("BabysitterCertificationInfo_AHA_FirstAid", resourceCulture);
            }
        }
        
        public static string BabysitterCertificationInfo_BabysitterBootCamp {
            get {
                return ResourceManager.GetString("BabysitterCertificationInfo_BabysitterBootCamp", resourceCulture);
            }
        }
        
        public static string BabysitterCertificationInfo_Other {
            get {
                return ResourceManager.GetString("BabysitterCertificationInfo_Other", resourceCulture);
            }
        }
        
        public static string BabysitterOtherCertifications {
            get {
                return ResourceManager.GetString("BabysitterOtherCertifications", resourceCulture);
            }
        }
        
        public static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        public static string CollegeStudent {
            get {
                return ResourceManager.GetString("CollegeStudent", resourceCulture);
            }
        }
        
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        public static string MiddleSchool {
            get {
                return ResourceManager.GetString("MiddleSchool", resourceCulture);
            }
        }
        
        public static string BabysitterEmployerHourlyRate {
            get {
                return ResourceManager.GetString("BabysitterEmployerHourlyRate", resourceCulture);
            }
        }
        
        public static string BabysitterEmployerCanDrive {
            get {
                return ResourceManager.GetString("BabysitterEmployerCanDrive", resourceCulture);
            }
        }
        
        public static string BabysitterEmployerOwnCar {
            get {
                return ResourceManager.GetString("BabysitterEmployerOwnCar", resourceCulture);
            }
        }
        
        public static string BabysitterEmployerDescriptionDefault {
            get {
                return ResourceManager.GetString("BabysitterEmployerDescriptionDefault", resourceCulture);
            }
        }
        
        public static string KidsInformation {
            get {
                return ResourceManager.GetString("KidsInformation", resourceCulture);
            }
        }
        
        public static string TennisAgeRange {
            get {
                return ResourceManager.GetString("TennisAgeRange", resourceCulture);
            }
        }
        
        public static string TennisSubdivision {
            get {
                return ResourceManager.GetString("TennisSubdivision", resourceCulture);
            }
        }
        
        public static string TennisZip {
            get {
                return ResourceManager.GetString("TennisZip", resourceCulture);
            }
        }
        
        public static string TennisFirstName {
            get {
                return ResourceManager.GetString("TennisFirstName", resourceCulture);
            }
        }
        
        public static string TennisDescriptionDefault {
            get {
                return ResourceManager.GetString("TennisDescriptionDefault", resourceCulture);
            }
        }
        
        public static string HasCourtAccess {
            get {
                return ResourceManager.GetString("HasCourtAccess", resourceCulture);
            }
        }
        
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        public static string Beginner {
            get {
                return ResourceManager.GetString("Beginner", resourceCulture);
            }
        }
        
        public static string BeginnerIntermediate {
            get {
                return ResourceManager.GetString("BeginnerIntermediate", resourceCulture);
            }
        }
        
        public static string Duce {
            get {
                return ResourceManager.GetString("Duce", resourceCulture);
            }
        }
        
        public static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        public static string IntermediateAdvanced {
            get {
                return ResourceManager.GetString("IntermediateAdvanced", resourceCulture);
            }
        }
        
        public static string NoPreference {
            get {
                return ResourceManager.GetString("NoPreference", resourceCulture);
            }
        }
        
        public static string PreferredSide {
            get {
                return ResourceManager.GetString("PreferredSide", resourceCulture);
            }
        }
        
        public static string Professional {
            get {
                return ResourceManager.GetString("Professional", resourceCulture);
            }
        }
        
        public static string SkillLevel {
            get {
                return ResourceManager.GetString("SkillLevel", resourceCulture);
            }
        }
        
        public static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        public static string EightToTwelve {
            get {
                return ResourceManager.GetString("EightToTwelve", resourceCulture);
            }
        }
        
        public static string FortyToSixty {
            get {
                return ResourceManager.GetString("FortyToSixty", resourceCulture);
            }
        }
        
        public static string FourteenToEighteen {
            get {
                return ResourceManager.GetString("FourteenToEighteen", resourceCulture);
            }
        }
        
        public static string LessThanTen {
            get {
                return ResourceManager.GetString("LessThanTen", resourceCulture);
            }
        }
        
        public static string Senior {
            get {
                return ResourceManager.GetString("Senior", resourceCulture);
            }
        }
        
        public static string SeventeenToThirty {
            get {
                return ResourceManager.GetString("SeventeenToThirty", resourceCulture);
            }
        }
        
        public static string TenToFourteen {
            get {
                return ResourceManager.GetString("TenToFourteen", resourceCulture);
            }
        }
        
        public static string ThirtyToFifty {
            get {
                return ResourceManager.GetString("ThirtyToFifty", resourceCulture);
            }
        }
        
        public static string TwelveToSixteen {
            get {
                return ResourceManager.GetString("TwelveToSixteen", resourceCulture);
            }
        }
        
        public static string TwentyToForty {
            get {
                return ResourceManager.GetString("TwentyToForty", resourceCulture);
            }
        }
        
        public static string TutorEmployerCanTravel {
            get {
                return ResourceManager.GetString("TutorEmployerCanTravel", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade {
            get {
                return ResourceManager.GetString("TutorEmployerGrade", resourceCulture);
            }
        }
        
        public static string TutorEmployerPreferredDate {
            get {
                return ResourceManager.GetString("TutorEmployerPreferredDate", resourceCulture);
            }
        }
        
        public static string TutorEmployerPreferredLength {
            get {
                return ResourceManager.GetString("TutorEmployerPreferredLength", resourceCulture);
            }
        }
        
        public static string TutorEmployerPreferredLocation {
            get {
                return ResourceManager.GetString("TutorEmployerPreferredLocation", resourceCulture);
            }
        }
        
        public static string TutorEmployerStudentName {
            get {
                return ResourceManager.GetString("TutorEmployerStudentName", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject {
            get {
                return ResourceManager.GetString("TutorEmployerSubject", resourceCulture);
            }
        }
        
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_College {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_College", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Eighth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Eighth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Eleventh {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Eleventh", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_First {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_First", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Fiveth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Fiveth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Fouth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Fouth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_k {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_k", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Ninth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Ninth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Second {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Second", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Seventh {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Seventh", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Sixth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Sixth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Tenth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Tenth", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Third {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Third", resourceCulture);
            }
        }
        
        public static string TutorEmployerGrade_Twelveth {
            get {
                return ResourceManager.GetString("TutorEmployerGrade_Twelveth", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject_Guitar {
            get {
                return ResourceManager.GetString("TutorEmployerSubject_Guitar", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject_OtherMusic {
            get {
                return ResourceManager.GetString("TutorEmployerSubject_OtherMusic", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject_Piano {
            get {
                return ResourceManager.GetString("TutorEmployerSubject_Piano", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject_Tennis {
            get {
                return ResourceManager.GetString("TutorEmployerSubject_Tennis", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubject_Violin {
            get {
                return ResourceManager.GetString("TutorEmployerSubject_Violin", resourceCulture);
            }
        }
        
        public static string TutorEmployerSubjectOther {
            get {
                return ResourceManager.GetString("TutorEmployerSubjectOther", resourceCulture);
            }
        }
        
        public static string TutorEmployerTutorEmployerSubjectOtherDefault {
            get {
                return ResourceManager.GetString("TutorEmployerTutorEmployerSubjectOtherDefault", resourceCulture);
            }
        }
        
        public static string TutorCanTravel_No {
            get {
                return ResourceManager.GetString("TutorCanTravel_No", resourceCulture);
            }
        }
        
        public static string TutorCanTravel_Yes {
            get {
                return ResourceManager.GetString("TutorCanTravel_Yes", resourceCulture);
            }
        }
        
        public static string TutorEmployerTutorEmployerPreferredLocationDefault {
            get {
                return ResourceManager.GetString("TutorEmployerTutorEmployerPreferredLocationDefault", resourceCulture);
            }
        }
        
        public static string TutorSubject_Chinese {
            get {
                return ResourceManager.GetString("TutorSubject_Chinese", resourceCulture);
            }
        }
        
        public static string TutorSubject_English {
            get {
                return ResourceManager.GetString("TutorSubject_English", resourceCulture);
            }
        }
        
        public static string TutorSubject_French {
            get {
                return ResourceManager.GetString("TutorSubject_French", resourceCulture);
            }
        }
        
        public static string TutorSubject_Math {
            get {
                return ResourceManager.GetString("TutorSubject_Math", resourceCulture);
            }
        }
        
        public static string TutorSubject_Other {
            get {
                return ResourceManager.GetString("TutorSubject_Other", resourceCulture);
            }
        }
        
        public static string TutorSubject_OtherLanguage {
            get {
                return ResourceManager.GetString("TutorSubject_OtherLanguage", resourceCulture);
            }
        }
        
        public static string TutorSubject_SATMath {
            get {
                return ResourceManager.GetString("TutorSubject_SATMath", resourceCulture);
            }
        }
        
        public static string TutorSubject_SATVerbal {
            get {
                return ResourceManager.GetString("TutorSubject_SATVerbal", resourceCulture);
            }
        }
        
        public static string TutorSubject_SATWriting {
            get {
                return ResourceManager.GetString("TutorSubject_SATWriting", resourceCulture);
            }
        }
        
        public static string TutorSubject_Science {
            get {
                return ResourceManager.GetString("TutorSubject_Science", resourceCulture);
            }
        }
        
        public static string TutorSubject_Spanish {
            get {
                return ResourceManager.GetString("TutorSubject_Spanish", resourceCulture);
            }
        }
        
        public static string PetSitterExpirience {
            get {
                return ResourceManager.GetString("PetSitterExpirience", resourceCulture);
            }
        }
        
        public static string PetSitterDropOff {
            get {
                return ResourceManager.GetString("PetSitterDropOff", resourceCulture);
            }
        }
        
        public static string PetSitterExpirienceOther {
            get {
                return ResourceManager.GetString("PetSitterExpirienceOther", resourceCulture);
            }
        }
        
        public static string PetSitterMultipleDaysDiscount {
            get {
                return ResourceManager.GetString("PetSitterMultipleDaysDiscount", resourceCulture);
            }
        }
        
        public static string PetSitterMultiplePetDiscount {
            get {
                return ResourceManager.GetString("PetSitterMultiplePetDiscount", resourceCulture);
            }
        }
        
        public static string PetSitterOtherRate {
            get {
                return ResourceManager.GetString("PetSitterOtherRate", resourceCulture);
            }
        }
        
        public static string PetSitterPetType {
            get {
                return ResourceManager.GetString("PetSitterPetType", resourceCulture);
            }
        }
        
        public static string PetSitterPetWeight {
            get {
                return ResourceManager.GetString("PetSitterPetWeight", resourceCulture);
            }
        }
        
        public static string PetSitter_Bird {
            get {
                return ResourceManager.GetString("PetSitter_Bird", resourceCulture);
            }
        }
        
        public static string PetSitter_Cat {
            get {
                return ResourceManager.GetString("PetSitter_Cat", resourceCulture);
            }
        }
        
        public static string PetSitter_Dog {
            get {
                return ResourceManager.GetString("PetSitter_Dog", resourceCulture);
            }
        }
        
        public static string PetSitter_Fish {
            get {
                return ResourceManager.GetString("PetSitter_Fish", resourceCulture);
            }
        }
        
        public static string PetSitter_Other {
            get {
                return ResourceManager.GetString("PetSitter_Other", resourceCulture);
            }
        }
        
        public static string PetSitter_Rodent {
            get {
                return ResourceManager.GetString("PetSitter_Rodent", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerAdditionalPetInformation {
            get {
                return ResourceManager.GetString("PetSitterEmployerAdditionalPetInformation", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerExpirienceRequired {
            get {
                return ResourceManager.GetString("PetSitterEmployerExpirienceRequired", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerExpirienceRequiredInformation {
            get {
                return ResourceManager.GetString("PetSitterEmployerExpirienceRequiredInformation", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerPetType {
            get {
                return ResourceManager.GetString("PetSitterEmployerPetType", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerPetWeight {
            get {
                return ResourceManager.GetString("PetSitterEmployerPetWeight", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerSearchable {
            get {
                return ResourceManager.GetString("PetSitterEmployerSearchable", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerSittersNotification {
            get {
                return ResourceManager.GetString("PetSitterEmployerSittersNotification", resourceCulture);
            }
        }
        
        public static string PetSitterEmployerSittersNotificationDistance {
            get {
                return ResourceManager.GetString("PetSitterEmployerSittersNotificationDistance", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer_FiveMiles {
            get {
                return ResourceManager.GetString("PetSitterEmployer_FiveMiles", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer_TenMiles {
            get {
                return ResourceManager.GetString("PetSitterEmployer_TenMiles", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer_TwentyMiles {
            get {
                return ResourceManager.GetString("PetSitterEmployer_TwentyMiles", resourceCulture);
            }
        }
        
        public static string TutorSubject_Guitar {
            get {
                return ResourceManager.GetString("TutorSubject_Guitar", resourceCulture);
            }
        }
        
        public static string TutorSubject_OtherMusic {
            get {
                return ResourceManager.GetString("TutorSubject_OtherMusic", resourceCulture);
            }
        }
        
        public static string TutorSubject_Piano {
            get {
                return ResourceManager.GetString("TutorSubject_Piano", resourceCulture);
            }
        }
        
        public static string TutorSubject_Tennis {
            get {
                return ResourceManager.GetString("TutorSubject_Tennis", resourceCulture);
            }
        }
        
        public static string TutorSubject_Violin {
            get {
                return ResourceManager.GetString("TutorSubject_Violin", resourceCulture);
            }
        }
        
        public static string TutorGrade {
            get {
                return ResourceManager.GetString("TutorGrade", resourceCulture);
            }
        }
        
        public static string TutorPreferredDate {
            get {
                return ResourceManager.GetString("TutorPreferredDate", resourceCulture);
            }
        }
        
        public static string TutorPreferredLength {
            get {
                return ResourceManager.GetString("TutorPreferredLength", resourceCulture);
            }
        }
        
        public static string TutorPreferredLocation {
            get {
                return ResourceManager.GetString("TutorPreferredLocation", resourceCulture);
            }
        }
        
        public static string TutorSubject {
            get {
                return ResourceManager.GetString("TutorSubject", resourceCulture);
            }
        }
        
        public static string TutorSubjectNote {
            get {
                return ResourceManager.GetString("TutorSubjectNote", resourceCulture);
            }
        }
        
        public static string TutorCanTravel {
            get {
                return ResourceManager.GetString("TutorCanTravel", resourceCulture);
            }
        }
        
        public static string TutorTutorPreferredLocationDefault {
            get {
                return ResourceManager.GetString("TutorTutorPreferredLocationDefault", resourceCulture);
            }
        }
        
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        public static string TutorSubjectOther {
            get {
                return ResourceManager.GetString("TutorSubjectOther", resourceCulture);
            }
        }
        
        public static string TutorTutorSubjectOtherDefault {
            get {
                return ResourceManager.GetString("TutorTutorSubjectOtherDefault", resourceCulture);
            }
        }
        
        public static string TutorGrade_Adult {
            get {
                return ResourceManager.GetString("TutorGrade_Adult", resourceCulture);
            }
        }
        
        public static string TutorGrade_College {
            get {
                return ResourceManager.GetString("TutorGrade_College", resourceCulture);
            }
        }
        
        public static string TutorGrade_Eleventh {
            get {
                return ResourceManager.GetString("TutorGrade_Eleventh", resourceCulture);
            }
        }
        
        public static string TutorGrade_Ninth {
            get {
                return ResourceManager.GetString("TutorGrade_Ninth", resourceCulture);
            }
        }
        
        public static string TutorGrade_Tenth {
            get {
                return ResourceManager.GetString("TutorGrade_Tenth", resourceCulture);
            }
        }
        
        public static string TutorGrade_Twelveth {
            get {
                return ResourceManager.GetString("TutorGrade_Twelveth", resourceCulture);
            }
        }
        
        public static string KidsPlayDateAdditionalInformation {
            get {
                return ResourceManager.GetString("KidsPlayDateAdditionalInformation", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredAgeRange {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredAgeRange", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredDateAndTime {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredDateAndTime", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredGender {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredGender", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredGender_Both {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredGender_Both", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredGender_Female {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredGender_Female", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredGender_Male {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredGender_Male", resourceCulture);
            }
        }
        
        public static string KidsPlayDateDesiredLocation {
            get {
                return ResourceManager.GetString("KidsPlayDateDesiredLocation", resourceCulture);
            }
        }
        
        public static string KidsPlayDateKidAge {
            get {
                return ResourceManager.GetString("KidsPlayDateKidAge", resourceCulture);
            }
        }
        
        public static string KidsPlayDateMyChild {
            get {
                return ResourceManager.GetString("KidsPlayDateMyChild", resourceCulture);
            }
        }
        
        public static string KidsPlayDateMyChild_SchoolFullTime {
            get {
                return ResourceManager.GetString("KidsPlayDateMyChild_SchoolFullTime", resourceCulture);
            }
        }
        
        public static string KidsPlayDateMyChild_SchoolPartTime {
            get {
                return ResourceManager.GetString("KidsPlayDateMyChild_SchoolPartTime", resourceCulture);
            }
        }
        
        public static string KidsPlayDateMyChild_StaysHome {
            get {
                return ResourceManager.GetString("KidsPlayDateMyChild_StaysHome", resourceCulture);
            }
        }
        
        public static string KidsPlayDateParentsInformation {
            get {
                return ResourceManager.GetString("KidsPlayDateParentsInformation", resourceCulture);
            }
        }
        
        public static string KidsPlayDatePreferredMethodOfPlay {
            get {
                return ResourceManager.GetString("KidsPlayDatePreferredMethodOfPlay", resourceCulture);
            }
        }
        
        public static string KidsPlayDateRace {
            get {
                return ResourceManager.GetString("KidsPlayDateRace", resourceCulture);
            }
        }
        
        public static string KidsPlayDateSpokenLanguage {
            get {
                return ResourceManager.GetString("KidsPlayDateSpokenLanguage", resourceCulture);
            }
        }
        
        public static string FitnessAdditionalInformation {
            get {
                return ResourceManager.GetString("FitnessAdditionalInformation", resourceCulture);
            }
        }
        
        public static string FitnessAgeRange {
            get {
                return ResourceManager.GetString("FitnessAgeRange", resourceCulture);
            }
        }
        
        public static string FitnessOther {
            get {
                return ResourceManager.GetString("FitnessOther", resourceCulture);
            }
        }
        
        public static string FitnessPreferredDateTime {
            get {
                return ResourceManager.GetString("FitnessPreferredDateTime", resourceCulture);
            }
        }
        
        public static string FitnessPreferredFrequency {
            get {
                return ResourceManager.GetString("FitnessPreferredFrequency", resourceCulture);
            }
        }
        
        public static string FitnessPreferredGender {
            get {
                return ResourceManager.GetString("FitnessPreferredGender", resourceCulture);
            }
        }
        
        public static string FitnessPreferredGender_Either {
            get {
                return ResourceManager.GetString("FitnessPreferredGender_Either", resourceCulture);
            }
        }
        
        public static string FitnessPreferredGender_Female {
            get {
                return ResourceManager.GetString("FitnessPreferredGender_Female", resourceCulture);
            }
        }
        
        public static string FitnessPreferredGender_Male {
            get {
                return ResourceManager.GetString("FitnessPreferredGender_Male", resourceCulture);
            }
        }
        
        public static string FitnessPreferredLocation {
            get {
                return ResourceManager.GetString("FitnessPreferredLocation", resourceCulture);
            }
        }
        
        public static string FitnessType {
            get {
                return ResourceManager.GetString("FitnessType", resourceCulture);
            }
        }
        
        public static string FitnessType_Basketball {
            get {
                return ResourceManager.GetString("FitnessType_Basketball", resourceCulture);
            }
        }
        
        public static string FitnessType_Biking {
            get {
                return ResourceManager.GetString("FitnessType_Biking", resourceCulture);
            }
        }
        
        public static string FitnessType_CardioDance {
            get {
                return ResourceManager.GetString("FitnessType_CardioDance", resourceCulture);
            }
        }
        
        public static string FitnessType_FlagFootball {
            get {
                return ResourceManager.GetString("FitnessType_FlagFootball", resourceCulture);
            }
        }
        
        public static string FitnessType_GroupFitness {
            get {
                return ResourceManager.GetString("FitnessType_GroupFitness", resourceCulture);
            }
        }
        
        public static string FitnessType_Gymming {
            get {
                return ResourceManager.GetString("FitnessType_Gymming", resourceCulture);
            }
        }
        
        public static string FitnessType_Hiking {
            get {
                return ResourceManager.GetString("FitnessType_Hiking", resourceCulture);
            }
        }
        
        public static string FitnessType_Jogging {
            get {
                return ResourceManager.GetString("FitnessType_Jogging", resourceCulture);
            }
        }
        
        public static string FitnessType_Other {
            get {
                return ResourceManager.GetString("FitnessType_Other", resourceCulture);
            }
        }
        
        public static string FitnessType_RockClimbing {
            get {
                return ResourceManager.GetString("FitnessType_RockClimbing", resourceCulture);
            }
        }
        
        public static string FitnessType_Soccer {
            get {
                return ResourceManager.GetString("FitnessType_Soccer", resourceCulture);
            }
        }
        
        public static string FitnessType_Softball {
            get {
                return ResourceManager.GetString("FitnessType_Softball", resourceCulture);
            }
        }
        
        public static string FitnessType_Walking {
            get {
                return ResourceManager.GetString("FitnessType_Walking", resourceCulture);
            }
        }
        
        public static string FitnessType_WeighTraining {
            get {
                return ResourceManager.GetString("FitnessType_WeighTraining", resourceCulture);
            }
        }
        
        public static string FitnessType_Yoga {
            get {
                return ResourceManager.GetString("FitnessType_Yoga", resourceCulture);
            }
        }
        
        public static string GolfAdditionalInformation {
            get {
                return ResourceManager.GetString("GolfAdditionalInformation", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup {
            get {
                return ResourceManager.GetString("GolfAgeGroup", resourceCulture);
            }
        }
        
        public static string GolfCourseType_Private {
            get {
                return ResourceManager.GetString("GolfCourseType_Private", resourceCulture);
            }
        }
        
        public static string GolfCourseType_Public {
            get {
                return ResourceManager.GetString("GolfCourseType_Public", resourceCulture);
            }
        }
        
        public static string GolfCourtPreference_Always {
            get {
                return ResourceManager.GetString("GolfCourtPreference_Always", resourceCulture);
            }
        }
        
        public static string GolfCourtPreference_Mostly {
            get {
                return ResourceManager.GetString("GolfCourtPreference_Mostly", resourceCulture);
            }
        }
        
        public static string GolfCourtPreference_NoPreference {
            get {
                return ResourceManager.GetString("GolfCourtPreference_NoPreference", resourceCulture);
            }
        }
        
        public static string GolfCourtPreference_NotPreferred {
            get {
                return ResourceManager.GetString("GolfCourtPreference_NotPreferred", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_EighteenToThirty {
            get {
                return ResourceManager.GetString("GolfAgeGroup_EighteenToThirty", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_ForteenToTwenty {
            get {
                return ResourceManager.GetString("GolfAgeGroup_ForteenToTwenty", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_FortyToSixty {
            get {
                return ResourceManager.GetString("GolfAgeGroup_FortyToSixty", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_LessThanEight {
            get {
                return ResourceManager.GetString("GolfAgeGroup_LessThanEight", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_Senior {
            get {
                return ResourceManager.GetString("GolfAgeGroup_Senior", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_SixToTwelve {
            get {
                return ResourceManager.GetString("GolfAgeGroup_SixToTwelve", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_TenToSixteen {
            get {
                return ResourceManager.GetString("GolfAgeGroup_TenToSixteen", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_ThirtyToFifty {
            get {
                return ResourceManager.GetString("GolfAgeGroup_ThirtyToFifty", resourceCulture);
            }
        }
        
        public static string GolfAgeGroup_TwentyTwoToForty {
            get {
                return ResourceManager.GetString("GolfAgeGroup_TwentyTwoToForty", resourceCulture);
            }
        }
        
        public static string GolfGreenFeeRangeWTP {
            get {
                return ResourceManager.GetString("GolfGreenFeeRangeWTP", resourceCulture);
            }
        }
        
        public static string GolfHandicap {
            get {
                return ResourceManager.GetString("GolfHandicap", resourceCulture);
            }
        }
        
        public static string GolfHomeCourseSubdivision {
            get {
                return ResourceManager.GetString("GolfHomeCourseSubdivision", resourceCulture);
            }
        }
        
        public static string GolfHomeCourseGreenFeeRange {
            get {
                return ResourceManager.GetString("GolfHomeCourseGreenFeeRange", resourceCulture);
            }
        }
        
        public static string GolfHomeCourseType {
            get {
                return ResourceManager.GetString("GolfHomeCourseType", resourceCulture);
            }
        }
        
        public static string GolfHomeCourseZip {
            get {
                return ResourceManager.GetString("GolfHomeCourseZip", resourceCulture);
            }
        }
        
        public static string GolfHomeCourtPreference {
            get {
                return ResourceManager.GetString("GolfHomeCourtPreference", resourceCulture);
            }
        }
        
        public static string GolfFirstName {
            get {
                return ResourceManager.GetString("GolfFirstName", resourceCulture);
            }
        }
        
        public static string KidsPlayDateFirstName {
            get {
                return ResourceManager.GetString("KidsPlayDateFirstName", resourceCulture);
            }
        }
        
        public static string PetSitterFirstName {
            get {
                return ResourceManager.GetString("PetSitterFirstName", resourceCulture);
            }
        }
        
        public static string TutorFirstName {
            get {
                return ResourceManager.GetString("TutorFirstName", resourceCulture);
            }
        }
        
        public static string HobbyType_BoardGaming {
            get {
                return ResourceManager.GetString("HobbyType_BoardGaming", resourceCulture);
            }
        }
        
        public static string HobbyType_VideoGaming {
            get {
                return ResourceManager.GetString("HobbyType_VideoGaming", resourceCulture);
            }
        }
        
        public static string HobbyAdditionalInformation {
            get {
                return ResourceManager.GetString("HobbyAdditionalInformation", resourceCulture);
            }
        }
        
        public static string HobbyAgeRange {
            get {
                return ResourceManager.GetString("HobbyAgeRange", resourceCulture);
            }
        }
        
        public static string HobbyOther {
            get {
                return ResourceManager.GetString("HobbyOther", resourceCulture);
            }
        }
        
        public static string HobbyPreferredDateTime {
            get {
                return ResourceManager.GetString("HobbyPreferredDateTime", resourceCulture);
            }
        }
        
        public static string HobbyPreferredLocation {
            get {
                return ResourceManager.GetString("HobbyPreferredLocation", resourceCulture);
            }
        }
        
        public static string HobbyType {
            get {
                return ResourceManager.GetString("HobbyType", resourceCulture);
            }
        }
        
        public static string HobbyType_Baking {
            get {
                return ResourceManager.GetString("HobbyType_Baking", resourceCulture);
            }
        }
        
        public static string HobbyType_BallroomDancing {
            get {
                return ResourceManager.GetString("HobbyType_BallroomDancing", resourceCulture);
            }
        }
        
        public static string HobbyType_BirdWatching {
            get {
                return ResourceManager.GetString("HobbyType_BirdWatching", resourceCulture);
            }
        }
        
        public static string HobbyType_Bookclub {
            get {
                return ResourceManager.GetString("HobbyType_Bookclub", resourceCulture);
            }
        }
        
        public static string HobbyType_Chess {
            get {
                return ResourceManager.GetString("HobbyType_Chess", resourceCulture);
            }
        }
        
        public static string HobbyType_Cooking {
            get {
                return ResourceManager.GetString("HobbyType_Cooking", resourceCulture);
            }
        }
        
        public static string HobbyType_Craft {
            get {
                return ResourceManager.GetString("HobbyType_Craft", resourceCulture);
            }
        }
        
        public static string HobbyType_Gardening {
            get {
                return ResourceManager.GetString("HobbyType_Gardening", resourceCulture);
            }
        }
        
        public static string HobbyType_Knitting {
            get {
                return ResourceManager.GetString("HobbyType_Knitting", resourceCulture);
            }
        }
        
        public static string HobbyType_Other {
            get {
                return ResourceManager.GetString("HobbyType_Other", resourceCulture);
            }
        }
        
        public static string HobbyType_Scrapbooking {
            get {
                return ResourceManager.GetString("HobbyType_Scrapbooking", resourceCulture);
            }
        }
        
        public static string HobbyType_Singing {
            get {
                return ResourceManager.GetString("HobbyType_Singing", resourceCulture);
            }
        }
        
        public static string OtherJobsAdditionalContactInfo {
            get {
                return ResourceManager.GetString("OtherJobsAdditionalContactInfo", resourceCulture);
            }
        }
        
        public static string OtherJobsAdditionalInformation {
            get {
                return ResourceManager.GetString("OtherJobsAdditionalInformation", resourceCulture);
            }
        }
        
        public static string OtherJobsAgeRange {
            get {
                return ResourceManager.GetString("OtherJobsAgeRange", resourceCulture);
            }
        }
        
        public static string OtherJobsExperiencey {
            get {
                return ResourceManager.GetString("OtherJobsExperiencey", resourceCulture);
            }
        }
        
        public static string OtherJobsLicense {
            get {
                return ResourceManager.GetString("OtherJobsLicense", resourceCulture);
            }
        }
        
        public static string OtherJobsOther {
            get {
                return ResourceManager.GetString("OtherJobsOther", resourceCulture);
            }
        }
        
        public static string OtherJobsOtherJobsAdditionalContactInfoDefault {
            get {
                return ResourceManager.GetString("OtherJobsOtherJobsAdditionalContactInfoDefault", resourceCulture);
            }
        }
        
        public static string OtherJobsOtherJobsExperienceyDefault {
            get {
                return ResourceManager.GetString("OtherJobsOtherJobsExperienceyDefault", resourceCulture);
            }
        }
        
        public static string OtherJobsOtherJobsReferenceDefault {
            get {
                return ResourceManager.GetString("OtherJobsOtherJobsReferenceDefault", resourceCulture);
            }
        }
        
        public static string OtherJobsPreferredDateTime {
            get {
                return ResourceManager.GetString("OtherJobsPreferredDateTime", resourceCulture);
            }
        }
        
        public static string OtherJobsReference {
            get {
                return ResourceManager.GetString("OtherJobsReference", resourceCulture);
            }
        }
        
        public static string OtherJobsType {
            get {
                return ResourceManager.GetString("OtherJobsType", resourceCulture);
            }
        }
        
        public static string OtherJobsType_BarTender {
            get {
                return ResourceManager.GetString("OtherJobsType_BarTender", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Caterer {
            get {
                return ResourceManager.GetString("OtherJobsType_Caterer", resourceCulture);
            }
        }
        
        public static string OtherJobsType_ComputerProgramming {
            get {
                return ResourceManager.GetString("OtherJobsType_ComputerProgramming", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Cooking {
            get {
                return ResourceManager.GetString("OtherJobsType_Cooking", resourceCulture);
            }
        }
        
        public static string OtherJobsType_GraphicDesign {
            get {
                return ResourceManager.GetString("OtherJobsType_GraphicDesign", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Handyman {
            get {
                return ResourceManager.GetString("OtherJobsType_Handyman", resourceCulture);
            }
        }
        
        public static string OtherJobsType_HouseCleaning {
            get {
                return ResourceManager.GetString("OtherJobsType_HouseCleaning", resourceCulture);
            }
        }
        
        public static string OtherJobsType_HouseSitting {
            get {
                return ResourceManager.GetString("OtherJobsType_HouseSitting", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Laundry {
            get {
                return ResourceManager.GetString("OtherJobsType_Laundry", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Nanny {
            get {
                return ResourceManager.GetString("OtherJobsType_Nanny", resourceCulture);
            }
        }
        
        public static string OtherJobsType_OfficeWork {
            get {
                return ResourceManager.GetString("OtherJobsType_OfficeWork", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Other {
            get {
                return ResourceManager.GetString("OtherJobsType_Other", resourceCulture);
            }
        }
        
        public static string OtherJobsType_PersonalAssistant {
            get {
                return ResourceManager.GetString("OtherJobsType_PersonalAssistant", resourceCulture);
            }
        }
        
        public static string OtherJobsType_PhotoEditing {
            get {
                return ResourceManager.GetString("OtherJobsType_PhotoEditing", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Photography {
            get {
                return ResourceManager.GetString("OtherJobsType_Photography", resourceCulture);
            }
        }
        
        public static string OtherJobsType_PressureWash {
            get {
                return ResourceManager.GetString("OtherJobsType_PressureWash", resourceCulture);
            }
        }
        
        public static string OtherJobs_ProfileRequirements {
            get {
                return ResourceManager.GetString("OtherJobs_ProfileRequirements", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Sales {
            get {
                return ResourceManager.GetString("OtherJobsType_Sales", resourceCulture);
            }
        }
        
        public static string OtherJobsType_SocialMedia {
            get {
                return ResourceManager.GetString("OtherJobsType_SocialMedia", resourceCulture);
            }
        }
        
        public static string OtherJobsType_SquirrelExtermination {
            get {
                return ResourceManager.GetString("OtherJobsType_SquirrelExtermination", resourceCulture);
            }
        }
        
        public static string OtherJobsType_Video {
            get {
                return ResourceManager.GetString("OtherJobsType_Video", resourceCulture);
            }
        }
        
        public static string OtherJobsType_VideoEditing {
            get {
                return ResourceManager.GetString("OtherJobsType_VideoEditing", resourceCulture);
            }
        }
        
        public static string OtherJobsType_WebDesign {
            get {
                return ResourceManager.GetString("OtherJobsType_WebDesign", resourceCulture);
            }
        }
        
        public static string OtherJobsType_WritingAndEditing {
            get {
                return ResourceManager.GetString("OtherJobsType_WritingAndEditing", resourceCulture);
            }
        }
        
        public static string OtherJobsType_YardWork {
            get {
                return ResourceManager.GetString("OtherJobsType_YardWork", resourceCulture);
            }
        }
        
        public static string OtherJobsAgeRange_Adult {
            get {
                return ResourceManager.GetString("OtherJobsAgeRange_Adult", resourceCulture);
            }
        }
        
        public static string OtherJobsAgeRange_CollegeStudent {
            get {
                return ResourceManager.GetString("OtherJobsAgeRange_CollegeStudent", resourceCulture);
            }
        }
        
        public static string OtherJobsAgeRange_HighSchool {
            get {
                return ResourceManager.GetString("OtherJobsAgeRange_HighSchool", resourceCulture);
            }
        }
        
        public static string OtherJobsAgeRange_MiddleSchool {
            get {
                return ResourceManager.GetString("OtherJobsAgeRange_MiddleSchool", resourceCulture);
            }
        }
        
        public static string Tennis_SearchResultsTitle {
            get {
                return ResourceManager.GetString("Tennis_SearchResultsTitle", resourceCulture);
            }
        }
        
        public static string Golf_SearchResultsTitle {
            get {
                return ResourceManager.GetString("Golf_SearchResultsTitle", resourceCulture);
            }
        }
        
        public static string Fitness_SearchResultsTitle {
            get {
                return ResourceManager.GetString("Fitness_SearchResultsTitle", resourceCulture);
            }
        }
        
        public static string Hobby_SearchResultsTitle {
            get {
                return ResourceManager.GetString("Hobby_SearchResultsTitle", resourceCulture);
            }
        }
        
        public static string OtherJobs_SearchResultsTitle {
            get {
                return ResourceManager.GetString("OtherJobs_SearchResultsTitle", resourceCulture);
            }
        }
    }
}
