// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mehspot.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MehspotStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MehspotStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mehspot.Core.MehspotStrings", typeof(MehspotStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Babysitter {
            get {
                return ResourceManager.GetString("Babysitter", resourceCulture);
            }
        }
        
        public static string BabysitterEmployer {
            get {
                return ResourceManager.GetString("BabysitterEmployer", resourceCulture);
            }
        }
        
        public static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        public static string Friendship {
            get {
                return ResourceManager.GetString("Friendship", resourceCulture);
            }
        }
        
        public static string Golf {
            get {
                return ResourceManager.GetString("Golf", resourceCulture);
            }
        }
        
        public static string Hobby {
            get {
                return ResourceManager.GetString("Hobby", resourceCulture);
            }
        }
        
        public static string KidsPlayDate {
            get {
                return ResourceManager.GetString("KidsPlayDate", resourceCulture);
            }
        }
        
        public static string OtherJobs {
            get {
                return ResourceManager.GetString("OtherJobs", resourceCulture);
            }
        }
        
        public static string PetSitter {
            get {
                return ResourceManager.GetString("PetSitter", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer {
            get {
                return ResourceManager.GetString("PetSitterEmployer", resourceCulture);
            }
        }
        
        public static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        public static string Tennis {
            get {
                return ResourceManager.GetString("Tennis", resourceCulture);
            }
        }
        
        public static string Tutor {
            get {
                return ResourceManager.GetString("Tutor", resourceCulture);
            }
        }
        
        public static string TutorEmployer {
            get {
                return ResourceManager.GetString("TutorEmployer", resourceCulture);
            }
        }
        
        public static string Babysitter_Description {
            get {
                return ResourceManager.GetString("Babysitter_Description", resourceCulture);
            }
        }
        
        public static string BabysitterEmployer_Description {
            get {
                return ResourceManager.GetString("BabysitterEmployer_Description", resourceCulture);
            }
        }
        
        public static string Fitness_Description {
            get {
                return ResourceManager.GetString("Fitness_Description", resourceCulture);
            }
        }
        
        public static string Friendship_Description {
            get {
                return ResourceManager.GetString("Friendship_Description", resourceCulture);
            }
        }
        
        public static string Golf_Description {
            get {
                return ResourceManager.GetString("Golf_Description", resourceCulture);
            }
        }
        
        public static string Hobby_Description {
            get {
                return ResourceManager.GetString("Hobby_Description", resourceCulture);
            }
        }
        
        public static string KidsPlayDate_Description {
            get {
                return ResourceManager.GetString("KidsPlayDate_Description", resourceCulture);
            }
        }
        
        public static string OtherJobs_Description {
            get {
                return ResourceManager.GetString("OtherJobs_Description", resourceCulture);
            }
        }
        
        public static string PetSitter_Description {
            get {
                return ResourceManager.GetString("PetSitter_Description", resourceCulture);
            }
        }
        
        public static string PetSitterEmployer_Description {
            get {
                return ResourceManager.GetString("PetSitterEmployer_Description", resourceCulture);
            }
        }
        
        public static string Sports_Description {
            get {
                return ResourceManager.GetString("Sports_Description", resourceCulture);
            }
        }
        
        public static string Tennis_Description {
            get {
                return ResourceManager.GetString("Tennis_Description", resourceCulture);
            }
        }
        
        public static string Tutor_Description {
            get {
                return ResourceManager.GetString("Tutor_Description", resourceCulture);
            }
        }
        
        public static string TutorEmployer_Description {
            get {
                return ResourceManager.GetString("TutorEmployer_Description", resourceCulture);
            }
        }
    }
}
